# config/config.yaml

# As chaves ficam vazias aqui. Vamos carregá-las por ambiente (.env)
# config/config.yaml

openai_key: null        # será lido do .env
gemini_key: null
anthropic_key: null
mistral_key: null
cohere_key: null

# Ordem global de fallback (você pode alterar)
fallback_chain:
  - openai
  - gemini
  - anthropic
  - mistral
  - cohere

notion_db:
  projects_db_id: "238ec5c5d2eb8093819eff542ae16463"
  tasks_db_id:    "238ec5c5d2eb801f9958e323667687d0"

team_capacity:
  - role: "Product Owner"
    hours_per_week: 10
  - role: "Desenvolvedor Full-Stack"
    hours_per_week: 40
  - role: "Designer UX/UI"
    hours_per_week: 20
  - role: "Gerente de Projeto"
    hours_per_week: 40

notifications:
  email:
    enabled: false
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    smtp_user: "seu-email@gmail.com"
    smtp_password: "sua-senha-de-app"

database_url: "sqlite:///projects.db"
backup:
  path: "backups/"
  daily_retention: 7
  weekly_retention: 4
  monthly_retention: 6

rules_file: config/rules.yaml
model_mapping_file: config/model_mapping.yaml
