# config/rules.yaml

event_workflows:
  NEW_PROJECT_CREATED:
    - analyze_market
    - analyze_compliance
    - plan_gtm
    - analyze_risks
    - design_org
    # - sync_notion   # se quiser sincronizar com Notion no fim

dependencies:
  Contract_Fabric:
    - Doc-Checklist_Builder
    - Compliance_Guardian
  Go-to-Market_Copilot:
    - FinModeler/Viability_Engine

priorities:
  - condition: "risk_score >= 8"
    level: "critical"
  - condition: "due_date_days <= 3"
    level: "high"
  - condition: "status == 'unlocked'"
    level: "medium"

capacity_rules:
  shared_resource_buffer_days: 2
  parallel_task_tolerance_percent: 80
