name: 🐳 Build & Publish Docker

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    name: Build e publica imagem no GHCR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push da imagem
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/agenteia:latest
            ghcr.io/${{ github.repository_owner }}/agenteia:${{ github.sha }}

      - name: Confirmação de publicação
        run: |
          echo "Imagem publicada: ghcr.io/${{ github.repository_owner }}/agenteia:latest"
